/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <stdint.h>
#include "stm32f407xx_gpio.h"

/*
 * @description: Toggles the orange led (LD3) connected to PD13
 * 				 of discovery board upon pressing user button
 * 				 (Falling Edge) connected to PA0 using Interrupt.
 */
int main(void)
{
	// Create Handle for GPIO configs.
	GPIO_Handle_t gpio;

	// Enable the clock for GPIOD.
	GPIO_ClockControl(GPIOD, ENABLE);
	// Enable the clock for GPIOA.
	GPIO_ClockControl(GPIOA, ENABLE);

	// Configure the parameters for GPIOD (LED - LD3).
	gpio.pGPIOx = GPIOD;
	gpio.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	gpio.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_13;
	gpio.GPIO_PinConfig.GPIO_PinOpType = GPIO_OTYPE_PUSHPULL;
	gpio.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PIN_PULLDOWN;

	// Initialize GPIOD-13 with required configs.
	GPIO_Init(&gpio);

	// Configure the parameters for GPIOA (User Button).
	gpio.pGPIOx = GPIOA;
	gpio.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_IT_FT;
	gpio.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_0;
	gpio.GPIO_PinConfig.GPIO_PinOpType = GPIO_OTYPE_PUSHPULL;

	// Configure the interrupt.
	GPIO_IRQInterruptConfig(IRQ_NO_EXTI0, ENABLE);
	GPIO_IRQPriorityConfig(IRQ_NO_EXTI0, 15);

	// Initialize GPIOA-0 with required configs.
	GPIO_Init(&gpio);

	// Infinite loop. (To test interrupt functionality)
	while(1);
}

void delay()
{
	// 200ms when CoreClock is at 16MHz (default).
	for(int i = 0; i < 500000/2; i++);
}

void EXTI0_IRQHandler(void)
{
	GPIO_TogglePin(GPIOD, GPIO_PIN_13);
	delay();
	GPIO_IRQHandler(0);
}
