/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "registers.h"

void delay(long int i)
{
        for(int d = 0; d < 300*i; d++);
}

int main(void)
{
        //AHB1ENR    => 0x40023800 + 0x30
        //GPIOE Mode => 0x40021000 + 0x00
        //GPIOE ODR  => 0x40021000 + 0x14

        //Initialize pointers to these registers
        volatile uint32_t *const pRCC   = (uint32_t*) 0x40023800;
        volatile uint32_t *const pGPIOE = (uint32_t*) 0x40021000;

        volatile RCC_AHB1ENR_t *const pRCC_AHB1ENR = (RCC_AHB1ENR_t*) (pRCC   + 12);
        volatile GPIOx_MODER *const pGPIOE_MODER = (GPIOx_MODER*) (pGPIOE + 0);
        volatile uint32_t *const pGPIOE_ODR =  (pGPIOE + 5);
        volatile GPIOx_PUPDR *const pGPIOE_PUPDR = (GPIOx_PUPDR*) (pGPIOE + 3);
        volatile uint32_t *const pGPIOE_IDR =  (pGPIOE + 4);

        const char keys[4][4] = {{'1','2','3','A'},
                                 {'4','5','6','B'},
                                 {'7','8','9','C'},
                                 {'*','0','#','D'}};

        //Enable Clock for GPIOE
    pRCC_AHB1ENR->gpioe_en = 1;

    pGPIOE_MODER->pin7 = 1;
    pGPIOE_MODER->pin8 = 1;
    pGPIOE_MODER->pin9 = 1;
    pGPIOE_MODER->pin10 = 1;
    pGPIOE_MODER->pin11 = 0;
    pGPIOE_MODER->pin12 = 0;
    pGPIOE_MODER->pin13 = 0;
    pGPIOE_MODER->pin14 = 0;

    pGPIOE_PUPDR->pin7 = 0;
    pGPIOE_PUPDR->pin8 = 0;
    pGPIOE_PUPDR->pin9 = 0;
    pGPIOE_PUPDR->pin10 = 0;
    pGPIOE_PUPDR->pin11 = 1;
    pGPIOE_PUPDR->pin12 = 1;
    pGPIOE_PUPDR->pin13 = 1;
    pGPIOE_PUPDR->pin14 = 1;

    while(1)
    {
        for(uint8_t i = 0; i < 4; i++)
        {
                *pGPIOE_ODR |= 0xF << 7;
                *pGPIOE_ODR &= ~(1 << (7+i));
                for(uint8_t j = 0; j < 4; j++)
                {
                        if(!(*pGPIOE_IDR & (1 << (11+j))))
                        {
                                delay(1000);
                                printf("%c\n",keys[i][j]);
                        }
                }
        }
    }
}
