/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
		//AHB1ENR    => 0x40023800 + 0x30
		//GPIOx Mode => 0x40020C00 + 0x00
		//GPIOx ODR  => 0x40020C00 + 0x14
		//GPIOx IDR  => 0x40020C00 + 0x10

		//Initialize pointers to these registers
	    uint32_t* pRCC   = (uint32_t*) 0x40023800;
	    uint32_t* pGPIOD = (uint32_t*) 0x40020C00;
	    uint32_t* pGPIOA = (uint32_t*) 0x40020000;

	    uint32_t* pRCC_AHB1ENR = (uint32_t*) ((uint32_t) pRCC   + 0x30);
	    uint32_t* pGPIOD_MODER = (uint32_t*) ((uint32_t) pGPIOD + 0x00);
	    uint32_t* pGPIOD_ODR   = (uint32_t*) ((uint32_t) pGPIOD + 0x14);
	    uint32_t* pGPIOA_MODER = (uint32_t*) ((uint32_t) pGPIOA + 0x00);
	    uint32_t* pGPIOA_IDR   = (uint32_t*) ((uint32_t) pGPIOA + 0x10);


	    //Enable Clock for GPIOD
	    *pRCC_AHB1ENR |= 9; //0x00000009

	    //Set GPIOD-12 Mode to Output Mode
	    //a. clear 24th and 25th bit
	    *pGPIOD_MODER &= ~(3 << 24);
	    *pGPIOD_MODER |=  (1 << 24);

	    *pGPIOA_MODER &= ~3;

	    while(1){
	    	uint8_t btnVal = *pGPIOA_IDR & 0x1;
	    	if(btnVal){
	    		*pGPIOD_ODR |=  (1 << 12);
	    	}else{
	    		*pGPIOD_ODR &= ~(1 << 12);
	    	}
	    }
}
